import Foundation

/// Display-only translations; unknown names always fall back to the source spelling.
public enum Names {
    public static let races = ["Australian Grand Prix":"澳大利亚大奖赛", "Chinese Grand Prix":"中国大奖赛", "Japanese Grand Prix":"日本大奖赛", "Bahrain Grand Prix":"巴林大奖赛", "Bahrain Grand Prix in Malaysia":"巴林大奖赛（马来西亚）", "Saudi Arabian Grand Prix":"沙特阿拉伯大奖赛", "Miami Grand Prix":"迈阿密大奖赛", "Canadian Grand Prix":"加拿大大奖赛", "Monaco Grand Prix":"摩纳哥大奖赛", "Barcelona Grand Prix":"巴塞罗那大奖赛", "Spanish Grand Prix":"西班牙大奖赛", "Austrian Grand Prix":"奥地利大奖赛", "British Grand Prix":"英国大奖赛", "Belgian Grand Prix":"比利时大奖赛", "Hungarian Grand Prix":"匈牙利大奖赛", "Dutch Grand Prix":"荷兰大奖赛", "Italian Grand Prix":"意大利大奖赛", "Azerbaijan Grand Prix":"阿塞拜疆大奖赛", "Singapore Grand Prix":"新加坡大奖赛", "United States Grand Prix":"美国大奖赛", "Mexico City Grand Prix":"墨西哥城大奖赛", "Brazilian Grand Prix":"巴西大奖赛", "São Paulo Grand Prix":"圣保罗大奖赛", "Las Vegas Grand Prix":"拉斯维加斯大奖赛", "Qatar Grand Prix":"卡塔尔大奖赛", "Abu Dhabi Grand Prix":"阿布扎比大奖赛", "Emilia Romagna Grand Prix":"艾米利亚-罗马涅大奖赛"]
    public static let countries = ["Australia":"澳大利亚", "China":"中国", "Japan":"日本", "Bahrain":"巴林", "Saudi Arabia":"沙特阿拉伯", "USA":"美国", "Canada":"加拿大", "Monaco":"摩纳哥", "Spain":"西班牙", "Austria":"奥地利", "UK":"英国", "Belgium":"比利时", "Hungary":"匈牙利", "Netherlands":"荷兰", "Italy":"意大利", "Azerbaijan":"阿塞拜疆", "Singapore":"新加坡", "Mexico":"墨西哥", "Brazil":"巴西", "Qatar":"卡塔尔", "UAE":"阿联酋", "Malaysia":"马来西亚"]
    public static let cities = ["Melbourne":"墨尔本", "Shanghai":"上海", "Suzuka":"铃鹿", "Sakhir":"萨基尔", "Jeddah":"吉达", "Miami":"迈阿密", "Montreal":"蒙特利尔", "Monte Carlo":"蒙特卡洛", "Barcelona":"巴塞罗那", "Madrid":"马德里", "Spielberg":"施皮尔贝格", "Silverstone":"银石", "Spa":"斯帕", "Budapest":"布达佩斯", "Zandvoort":"赞德沃特", "Monza":"蒙扎", "Baku":"巴库", "Marina Bay":"滨海湾", "Austin":"奥斯汀", "Mexico City":"墨西哥城", "São Paulo":"圣保罗", "Las Vegas":"拉斯维加斯", "Lusail":"卢赛尔", "Abu Dhabi":"阿布扎比", "Kuala Lumpur":"吉隆坡", "Imola":"伊莫拉"]
    public static let circuits = ["albert_park":"阿尔伯特公园赛道", "shanghai":"上海国际赛车场", "suzuka":"铃鹿赛道", "bahrain":"巴林国际赛道", "jeddah":"吉达滨海赛道", "miami":"迈阿密国际赛道", "villeneuve":"吉尔·维伦纽夫赛道", "monaco":"摩纳哥赛道", "catalunya":"巴塞罗那-加泰罗尼亚赛道", "madring":"马德里赛道", "red_bull_ring":"红牛环赛道", "silverstone":"银石赛道", "spa":"斯帕-弗朗科尔尚赛道", "hungaroring":"亨格罗宁赛道", "zandvoort":"赞德沃特赛道", "monza":"蒙扎国家赛车场", "baku":"巴库城市赛道", "marina_bay":"滨海湾街道赛道", "americas":"美洲赛道", "rodriguez":"罗德里格斯兄弟赛道", "interlagos":"英特拉格斯赛道", "vegas":"拉斯维加斯大道赛道", "losail":"卢赛尔国际赛道", "yas_marina":"亚斯码头赛道", "sepang":"雪邦国际赛道", "imola":"伊莫拉赛道"]
    public static let teams = ["mercedes":"梅赛德斯", "ferrari":"法拉利", "mclaren":"迈凯伦", "red_bull":"红牛", "aston_martin":"阿斯顿·马丁", "alpine":"阿尔派", "haas":"哈斯", "williams":"威廉姆斯", "rb":"Racing Bulls", "sauber":"索伯", "audi":"奥迪", "cadillac":"凯迪拉克"]
    public static let drivers = ["antonelli":"安东内利", "russell":"拉塞尔", "hamilton":"汉密尔顿", "leclerc":"勒克莱尔", "norris":"诺里斯", "piastri":"皮亚斯特里", "max_verstappen":"维斯塔潘", "hadjar":"哈贾尔", "lawson":"劳森", "lindblad":"林德布拉德", "arvid_lindblad":"林德布拉德", "alonso":"阿隆索", "stroll":"斯特罗尔", "gasly":"加斯利", "colapinto":"科拉平托", "albon":"阿尔本", "sainz":"塞恩斯", "ocon":"奥康", "bearman":"贝尔曼", "hulkenberg":"霍肯伯格", "bortoleto":"博托莱托", "bottas":"博塔斯", "perez":"佩雷兹", "tsunoda":"角田裕毅", "zhou":"周冠宇", "ricciardo":"里卡多", "magnussen":"马格努森", "doohan":"杜汉"]
    public static let zones = ["albert_park":"Australia/Melbourne", "shanghai":"Asia/Shanghai", "suzuka":"Asia/Tokyo", "bahrain":"Asia/Bahrain", "jeddah":"Asia/Riyadh", "miami":"America/New_York", "villeneuve":"America/Toronto", "monaco":"Europe/Monaco", "catalunya":"Europe/Madrid", "madring":"Europe/Madrid", "red_bull_ring":"Europe/Vienna", "silverstone":"Europe/London", "spa":"Europe/Brussels", "hungaroring":"Europe/Budapest", "zandvoort":"Europe/Amsterdam", "monza":"Europe/Rome", "baku":"Asia/Baku", "marina_bay":"Asia/Singapore", "americas":"America/Chicago", "rodriguez":"America/Mexico_City", "interlagos":"America/Sao_Paulo", "vegas":"America/Los_Angeles", "losail":"Asia/Qatar", "yas_marina":"Asia/Dubai", "sepang":"Asia/Kuala_Lumpur", "imola":"Europe/Rome"]
}
